name: Backend Workflow
on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
jobs:
  build:
    name: Build, Test and Deploy
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
      - name: Test and Build
        run: ./gradlew build
      - name: Render deploy
        uses: distributhor/workflow-webhook@v3
        if: ${{ secrets.BACKEND_DEPLOY_HOOK }} != ""
        env:
          webhook_url: ${{ secrets.BACKEND_DEPLOY_HOOK }}&ref=${{ env.GITHUB_SHA }}
