name: Frontend Workflow
on:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**'
jobs:
  build:
    name: Build, Test and Deploy
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - uses: actions/cache@v2
        id: playwright-cache
        with:
         path: |
           ~/.cache/ms-playwright
         key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: yarn playwright install-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 15
      - name: Render deploy
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.FRONTEND_DEPLOY_HOOK }}
